### ISSUE TITLE
Clicking on "i" icon causes "Recoverable fatal error" message

### ISSUE THREAD

**Issue by KotM** [BoardTools/cronstatus#10]
1. Open Cron Status page in acp
2. Click on "i" icon
3. The following error will be displayed:

> Recoverable fatal error: Object of class phpbb\config\db could not be converted to string in \phpbb\extension\metadata_manager.php on line 49

Cron Status 3.1.2
phpBB 3.2.5

**Comment by lavigor** [comment]
@KotM, thank you for the report.
Could you please test it with the latest development version (3.1.3-dev)?
This problem should have already been fixed in this repository.

**Comment by KotM** [comment]
Yep, it looks fine on the dev version.
