### ISSUE TITLE
postgres compatibility

### ISSUE THREAD

**Issue by bastianh** [BoardTools/cronstatus#4]
Hi,

your extension is not compatible with postgres because it uses wrong quotes in sql.

```
SQL ERROR [ postgres ]

ERROR: column "%_gc" does not exist LINE 1: ...ig_value FROM phpbb_config WHERE config_name LIKE "%_gc" OR ... ^ []

SQL

SELECT config_name, config_value FROM phpbb_config WHERE config_name LIKE "%_gc" OR config_name = "last_queue_run" OR config_name = "queue_interval"
```

the problem is that double quotes are accepted in mysql, but the sql standard only allows single quotes for that. ( double quotes are used for system identifiers, field names and table names, but not strings )

http://stackoverflow.com/questions/1992314/what-is-the-difference-between-single-and-double-quotes-in-sql

Bastian

**Comment by lavigor** [comment]
Thank you for your response!
Please check out whether my solution works for you.

**Comment by bastianh** [comment]
thanks... looks like everything works now
