### ISSUE TITLE
duplicate font-awesome reference (phpBB 3.2)

### ISSUE THREAD

**Issue by rookey** [BoardTools/cronstatus#7]
Hello,

great extension!

font-awesome.css gets loaded from adm/style/acp_ext_details.html and acp_cronstatus.html although already getting loaded by the prosilver template.
This leads to additional loading times and a slower website. It is questionable anyway why it would be necessary just to check cronjobs. Maybe it can be removed for future versions.

thanks! r.

**Comment by lavigor** [comment]
Hello, @rookey.
This extension has nothing to do with prosilver, it is for ACP only.
Font Awesome isn't loaded twice anywhere for this extension.
