### ISSUE TITLE
Fatal Error with phpBB-3.2

### ISSUE THREAD

**Issue by kilianr** [BoardTools/cronstatus#8]
Installing works fine, but when clicking on the "Check Cron Status" link, I get:

> Fatal error: Uncaught TypeError: Argument 5 passed to pico\autodbbackup\cron\task\auto_db_backup::__construct() must be an instance of phpbb\db\tools, instance of phpbb\db\tools\tools given, called in /var/www/localhost/htdocs/cache/production/container_dbdbe80dc7030ae9bd39ee30cca82130.php on line 3415 and defined in /var/www/localhost/htdocs/ext/pico/autodbbackup/cron/task/auto_db_backup.php:26 Stack trace: #0 /var/www/localhost/htdocs/cache/production/container_dbdbe80dc7030ae9bd39ee30cca82130.php(3415): pico\autodbbackup\cron\task\auto_db_backup->__construct('./../', 'php', Object(phpbb\config\db), Object(phpbb\db\driver\factory), Object(phpbb\db\tools\tools), Object(phpbb\log\log), Object(phpbb\user)) #1 /var/www/localhost/htdocs/vendor/symfony/dependency-injection/Container.php(314): phpbb_cache_container->getPico_Autodbbackup_Cron_Task_Core_AutoDbBackupService() #2 /var/www/localhost/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(447): Symfony\Component\D in /var/www/localhost/htdocs/ext/pico/autodbbackup/cron/task/auto_db_backup.php on line 26

**Comment by jczstudios** [comment]
+1

**Comment by lavigor** [comment]
Sorry for the late reply, it seems to be the problem with that cron task in `pico\autodbbackup` extension.
Have you contacted the author of that extension?
You should probably have the same errors in your servers' error logs.

**Comment by lavigor** [comment]
Please use the 3.2-compatible version of that extension.
https://www.phpbb.com/community/viewtopic.php?f=456&t=2400156
