### ISSUE TITLE
addslashes_recursively is removed in current phpBB

### ISSUE THREAD

**Issue by BarryCarlyon** [BoardTools/cronstatus#9]
> Uncaught Error: Call to undefined method phpbb\request\type_cast_helper::addslashes_recursively()

May dig and try to fix. Don't have time right now

Versions:
phpBB: 3.2.5
php: 7.2.10
extension: 3.1.2

**Comment by KotM** [comment]
Simple fix:

examine _\ext\boardtools\cronstatus\acp\cronstatus_module.php_, find 
`$type_cast_helper->addslashes_recursively($cron_url);`
replace by 
`addslashes($cron_url);`

Hope it will be fixed in nearest releases.

**Comment by lavigor** [comment]
...and this has been removed from the extension too.
The replacement suggested by @KotM has already been made in the repository.
It's just that I haven't had enough time to upload the fixed release to the CDB yet, sorry for that.
